stages:
  - build
  - deploy

build_image:
  stage: build
  image: 
      name: gcr.io/kaniko-project/executor:v1.18.0-debug
      entrypoint: [""]
  variables:
    BUILD_TARGET: "release"
    BUILD_CONTEXT: $CI_PROJECT_DIR
    DOCKERFILE_LOCATION: $CI_PROJECT_DIR/Dockerfile
    BUILD_TAG: $CI_COMMIT_SHA

  script:
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --target "${BUILD_TARGET}"
      --context "${BUILD_CONTEXT}"
      --dockerfile "${DOCKERFILE_LOCATION}"
      --destination "${ECR_REPOSITORY_URL}:${BUILD_TAG}"
      --destination "${ECR_REPOSITORY_URL}:${CI_COMMIT_REF_SLUG}"

deploy:
  stage: deploy
  image: alpine:3.8
  variables:
    BUILD_TAG: $CI_COMMIT_SHA
  before_script:
    - apk add --no-cache git curl bash coreutils
    - git clone https://${CI_USERNAME}:${CI_PUSH_TOKEN}@${INFRASTRUCTURE_REPOSITORY}
    - cd infrastructure
    - git config --global user.email "gitlab@gitlab.com"
    - git config --global user.name "GitLab CI/CD"
    - git checkout -B main
    - git pull origin main
    - pip install -r requirements.txt
  script:
    - chmod +x ./update 
    - ./update "${DEPLOYMENT_NAME}" "${ECR_REPOSITORY_URL}:${BUILD_TAG}"
    - git commit -am "[skip ci] Updated ${PROJECT_DIR_NAME} image tag to ${DEPLOY_TAG}"
    - git push origin main

  only:
    - master  
